services:
  backend:
    build: ./backend
    ports:
      - '4035:3030'
    environment:
      - PORT=3030
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ws://localhost:4035
    ports:
      - 80:3000
